spring.application.name=testeSubmissao

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/onlinejudge
spring.datasource.username=postgres
spring.datasource.password=#Rezende31
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Flyway (para rodar o V1__init_schema.sql automaticamente)
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration